APP:
  NAME: otp-service
  VERSION: 1.0.0
  MODE: debug

HTTP:
  PORT: 9999
  READ_TIMEOUT: 10s
  WRITE_TIMEOUT: 30s
  IDLE_TIMEOUT: 30s
  SHUTDOWN_TIMEOUT: 5s
  USE_PREFORK_MODE: false
  API_TIMEOUT: 5s

LOG:
  LEVEL: debug
  IN_COMMING_REQUEST:
    PRINT_REQUEST: true
    PRINT_RESPONSE: true
  OUT_COMMING_REQUEST:
    PRINT_REQUEST: true
    PRINT_RESPONSE: true
PG:
  POOL_MAX: 10
  POOL_MIN: 2
  MAX_CONN_LIFETIME: 30m
  MAX_CONN_IDLE_TIME: 10m
  HEALTH_CHECK_PERIOD: 1m
  URL: "postgres://app_otp:app_otp2026@localhost:5432/otp?sslmode=disable"

REDIS:
  URL: "redis://:Ecomsecret@localhost:6379/0"


METRICS:
  ENABLED: true
  SKIP_PATHS: "/swagger/*;/metrics;/debug/*"
  PATH: "/metrics"